name: Test

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_course_definition:
    uses: andy1li/course-sdk/.github/workflows/test-course-definition.yml@main
